apiVersion: v1
kind: ConfigMap
metadata:
  name: crypto-config # Đặt tên chung
  namespace: crypto-system
data:
  KAFKA_BROKER: "kafka:9092"
  PG_HOST: "postgres"
  PG_PORT: "5432"
  PG_DB: "cryptodb"
  # Lưu ý: Tên service trong minio.yaml của Minh là minio-service
  MINIO_ENDPOINT: "http://minio-service:9000" 
  INFLUX_URL: "http://influxdb:8086"